### ISSUE TITLE
Usage with Create React App

### ISSUE THREAD

**Issue by craigcoles** [repetere/rjx#4]
This is an awesome library that pretty much solves an issue I am trying to solve.

The only issue I am having is getting this to play nicely with Create React App. Is that even possible?

**Comment by yawetse** [comment]
Yes it does, I have a sample project I'm putting together with create react app, it'll probably be ready in like a month. if you need something before that let me know.

**Comment by craigcoles** [comment]
@yawetse I tried to get it up and running yesterday with Create React App, but was having issues and Webpack was throwing an error. I could get an example over to you if that helps?

**Comment by yawetse** [comment]
@craigcoles absolutely. here's the start of the project https://github.com/repetere/rajax-core the repo was private because I'm still working on it, but take a look at how I've integrated create react app, you can fork it, or clone it and take it in the direction you need.

I'd love to hear your general feedback on RJX and if you think there's anything obvious missing

**Comment by craigcoles** [comment]
@yawetse Massive thanks! Just going to pull it down now and have a play with it 👍

**Comment by craigcoles** [comment]
@yawetse I managed to get it working with my current app now. I was importing incorrectly:

```js
// Throws an error
import { default as rjx } from 'rjx';

// Works
import * as RJX from 'rjx/src/main';
```

---

In terms of the project, it pretty much suits my use case. I want to be able to use JSON to generate and create a react app. I've done a lot of searching around, the only thing I managed to find anywhere near close was [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form).

**Comment by craigcoles** [comment]
I've ran into an issue when trying to build using Create React App now 😓 

```
$ yarn run build
yarn run v1.3.2
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/rjx/src/main.js:11 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yawetse** [comment]
what version of react?

**Comment by craigcoles** [comment]
```
"react": "16.3.2",
"react-scripts": "1.1.4"
```

**Comment by yawetse** [comment]
did you try running create reactapp build on https://github.com/repetere/rajax-core ?

**Comment by craigcoles** [comment]
@yawetse I haven't as of yet, I shall give it a try 👍

**Comment by craigcoles** [comment]
@yawetse Just tested on `rajax-core` and I am getting the same issue.

**Comment by yawetse** [comment]
hrmmm I found out what the issue is, babel doesnt like how i'm importing modules in RJX, will push out a fix shortly

**Comment by yawetse** [comment]
ok two options (all related to how you import RJX)
```javascript
//change 
import * as RJX from 'rjx/src/main';
//you can use require instead
const RJX = require('rjx');
//or import the correct ESM module
import * as RJX from 'rjx/dist/rjx.esm';
```

**Comment by craigcoles** [comment]
@yawetse Awesome stuff! Cheers!

**Comment by yawetse** [comment]
the issue is `rjx/src/main` is es2017/esnext but since it's in node_modules it wont get compiled in babel via create react app unless you change the webpack config. RJX does export a transpiled ES Modules in the dist folder
