### ISSUE TITLE
componentLibraries vs reactComponents

### ISSUE THREAD

**Issue by craigcoles** [repetere/rjx#7]
What is the difference between surrounding `componentLibraries` and `reactComponents`? In my application, the naming conventions range from:

```jsx
<Button/>
<Layout.Full/>
<Layout.Center/>
<Select/>
<Select.Item/>
<Menu/>
```

These are all my own custom components.

**Comment by yawetse** [comment]
I haven't looked at this in awhile but, i believe the main difference is a component Library is an object with multiple components (like Semantic UI) - https://github.com/repetere/rjx#advanced---using-custom-components--ui-libraries
```javascript
const Semantic = {
  Component1,
  Component2,
}
```

I believe those subcomponents can be nested Component.SubComponent 

In your case, I think you want to use reactComponents, where you pass an object with all of custom components you want to use: https://github.com/repetere/rjx#advanced---using-custom-components--ui-libraries

The only issues I see is `Layout.Full` would not be a valid object property name, so you may effectively have a "library" called "Layout" and in RJX you could reference your components as "Layout.Full"

**Comment by craigcoles** [comment]
I did think `ReactComponents` would be the correct one for my use case, but it kept complaining about`Layout.Full`.

# Example

*Helpers/RJX.js*
```jsx
import * as RJX from 'rjx/src/main';
import Components from "Components";

const getRenderedJSON = RJX.getRenderedJSON.bind({
  reactComponents: {
    Components
  }
});

export default getRenderedJSON;
```

*Scenes/Test.js*
```jsx
import React, { Component } from "react";
import getRenderedJSON from 'Helpers/RJX';

const data = {
  "component": "Layout.Full",
  "children": [
    {
      "component": "Text",
      "children": "Hello World!"
    }
  ]
}

export default class Test extends Component {
  render() {
    return getRenderedJSON(data)
  }
}
```

## Result

![](https://user-images.githubusercontent.com/996430/41363351-8edff74c-6f2b-11e8-82db-6b5cd256912e.png)

**Comment by yawetse** [comment]
@craigcoles another option (depending on how complicated your `Layout` components are) because you can define the components completely in JSON if you want https://github.com/repetere/rjx#advanced---custom-react-components--lifecycle-functions

**Comment by yawetse** [comment]
can you show me what `import Components from "Components";` what's contained in Components?

**Comment by yawetse** [comment]
try this:

Helpers/RJX.js
```javascript
import * as RJX from 'rjx/src/main';
import {Components as Layout} from "Components";

const getRenderedJSON = RJX.getRenderedJSON.bind({
  reactComponents: {
    Layout,
  }
});

export default getRenderedJSON;
```

**Comment by craigcoles** [comment]
In terms of the `Layout` component, its just a combination of small components as shown:

*Components/Layout/index.js*
```jsx
function Center(props: Props): React$Element<any> {
  ...
}

function Full(props: Props): React$Element<any> {
  ...
}

function Padded(props: Props): React$Element<any> {
  ...
}

const Layout = {
  Center,
  Full,
  Padded
};

export default Layout;
```


*Components/index.js*
```jsx
import Button from 'Components/Button';
import Layout from 'Components/Layout';
import Select from 'Components/Select';
import Menu from 'Components/Menu';

export default {
  Button,
  Layout,
  Select,
  Menu
};
```

**Comment by yawetse** [comment]
do your other components work (like Button, Select and Menu)?

**Comment by craigcoles** [comment]
They do not 🤔 This is what I have just tested:

```JSX
const data = {
  "component": "Text",
  "children": "Hello World!"
}
```

**Comment by yawetse** [comment]
So by default the only available components come from ReactDOM, so 'div' or 'textarea' etc so `component:"Text"` won't work because it's not defined

**Comment by yawetse** [comment]
also for your components, you want to use a component library

**Comment by yawetse** [comment]
this is a good example: https://github.com/repetere/rjx/blob/master/test/unit/components_spec.js#L137

```javascript
import * as RJX from 'rjx/src/main';
import Components from "Components";

const componentLibraries = {
      Components,
    };

const getRenderedJSON = RJX.getRenderedJSON.bind({
 componentLibraries,
});

export default getRenderedJSON;
```

**Comment by yawetse** [comment]
Then you would reference it like this:

```javascript
import React, { Component } from "react";
import getRenderedJSON from 'Helpers/RJX';

const data = {
  "component": "Components.Layout.Full",
  "children": [
    {
      "component": "Text",
      "children": "Hello World!"
    }
  ]
}

export default class Test extends Component {
  render() {
    return getRenderedJSON(data)
  }
}

```

**Comment by craigcoles** [comment]
@yawetse Massive thanks! I have it working using your example!
